In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import glob
print("Libraries loaded")

Libraries loaded

In [2]:
files = glob.glob("../data/*.parquet")
print("Number of files:", len(files))
files[:3]

Number of files: 12

['../data/yellow_tripdata_2015-10.parquet',
 '../data/yellow_tripdata_2015-09.parquet',
 '../data/yellow_tripdata_2015-08.parquet']

In [3]:
df = pd.read_parquet(
    "../data/yellow_tripdata_2015-01.parquet"
)
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,1,2015-01-01 00:11:33,2015-01-01 00:16:48,1,1.0,1,N,41,166,1,5.7,0.5,0.5,1.40,0.0,0.0,8.40,None,None
1,1,2015-01-01 00:18:24,2015-01-01 00:24:20,1,0.9,1,N,166,238,3,6.0,0.5,0.5,0.00,0.0,0.0,7.30,None,None
2,1,2015-01-01 00:26:19,2015-01-01 00:41:06,1,3.5,1,N,238,162,1,13.2,0.5,0.5,2.90,0.0,0.0,17.40,None,None
3,1,2015-01-01 00:45:26,2015-01-01 00:53:20,1,2.1,1,N,162,263,1,8.2,0.5,0.5,2.37,0.0,0.0,11.87,None,None
4,1,2015-01-01 00:59:21,2015-01-01 01:05:24,1,1.0,1,N,236,141,3,6.0,0.5,0.5,0.00,0.0,0.0,7.30,None,None

# Dataset Overview

In [4]:
df.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'airport_fee'],
      dtype='str')

In [5]:
df.dtypes

VendorID                          int64
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                   int64
trip_distance                   float64
RatecodeID                        int64
store_and_fwd_flag                  str
PULocationID                      int64
DOLocationID                      int64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge             object
airport_fee                      object
dtype: object

In [6]:
# Boş sütunları kaldır
df = df.dropna(axis=1, how="all")

print("Remaining columns:", len(df.columns))

Remaining columns: 17

In [7]:
df.columns # 'congestion_surcharge' ve 'airport_fee' sütunları kaldırıldı

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount'],
      dtype='str')

In [8]:
print("Dataset shape:", df.shape)

Dataset shape: (12741035, 17)

In [9]:
df.isnull().sum()

VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
PULocationID             0
DOLocationID             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    3
total_amount             0
dtype: int64

In [10]:
# pickup sütununu datetime türüne dönüştürülmesi
df["tpep_pickup_datetime"] = pd.to_datetime(
    df["tpep_pickup_datetime"]
)
# saatlik yolculuk sayısı oluşturulması
hourly_data = (
    df.set_index("tpep_pickup_datetime")
    .resample("h")
    .size()
    .reset_index(name="trip_count")
)
hourly_data.head()

  tpep_pickup_datetime  trip_count
0  2015-01-01 00:00:00       28312
1  2015-01-01 01:00:00       31707
2  2015-01-01 02:00:00       28068
3  2015-01-01 03:00:00       24288
4  2015-01-01 04:00:00       17081

In [11]:
hourly_data.shape

(744, 2)